stages:
  - build
  - accessibility

build:app
  stage: build
  image: cypress/browser:latest
  script:
    - cd accessibility-test
    - npm run cy:build
  artifacts:
    when: always
    expire_in: "30 days"
    paths:
      - "accessibility-test/cypress/video/"
      - "accessibility-test/cypress/screenshots/"
  only:
    - main

    accessibility:chrome:
     stage: accessibility
  image: cypress/browser:latest
  script:
    - cd accessibility-test
    - npm run cy:build
    - npm run cy:run
  artifacts:
    when: always
    expire_in: "30 days"
    paths:
      - "accessibility-test/cypress/video/"
      - "accessibility-test/cypress/screenshots/"
  only:
  - main